name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Check out code
        uses: actions/checkout@v3

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests
        run: |
          pytest

  push-to-docker-hub:
            needs: build-and-test
            runs-on: ubuntu-latest
            steps:
              - name: Check out code
                uses: actions/checkout@v3
        
              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
        
              - name: Log in to Docker Hub
                run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
              - name: Build Docker image
                run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
        
              - name: Push Docker image
                run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest